### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by RemiBou** [OliaG/ml.net-examples#2]
Which nuget package source are you using ? I got the following error

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NU1101	Unable to find package Microsoft.ML.symbols. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	GitHubLabeler	C:\Users\Rémi\source\repos\ml.net-examples\GitHubLabeler\GitHubLabeler\GitHubLabeler.csproj	1	

Maybe we can add the good nuget.config file to the repo.

**Comment by OliaG** [comment]
My bad, forgot to update to the latest nuget version. Thanks for the PR. Fixed now.
